
on:
    push: 
        branches: 
            - main


name: Build & Test Application


jobs:


    build-linux:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkcout@v4

            - 
                name: Install dependencies
                run: npm install

            -
                name: Build packages
                run: npm run build

            -
                name: Run tests
                run: npx vitest test

            -
                name: Build executable
                run: npm run only:dist:linux

    build-win:

        runs-on: windows-latest

        steps:
            - uses: actions/checkcout@v4

            - 
                name: Install dependencies
                run: npm install

            -
                name: Build packages
                run: npm run build

            -
                name: Run tests
                run: npx vitest test

            -
                name: Build executable
                run: npm run only:dist:win

            

