
on:
    push: 
        branches: 
            - main


name: Build & Test Application


jobs:
    
    main:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - 
                name: Install dependencies
                run: npm install
            

            -
                name: Build project
                run: npm run build

            -
                name: Run tests
                run: npx vitest test
            
            -
                name: Run linux build
                run: npm run only:dist:linux
            
            -
                name: Run win build
                run: npm run only:dist:win

            

