
on:
    push: 
        branches: 
            - main


name: Build & Test Application


jobs:

    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            -
                name: Install dependencies
                run: npm install
            
            -
                name: Build packages
                run: npm run build
            
            -
                name: Test
                run: npm run test

    build-linux:
        
        needs: tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - 
                name: Install dependencies
                run: npm install

            -
                name: Build
                run: npm run dist:linux

    build-win:

        needs: tests
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - 
                name: Install dependencies
                run: npm install

            -
                name: Build executable
                run: npm run dist:win

            

